# -*- coding: utf-8 -*-
"""RealWorld_Data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ujc2YrkgTXnc8MxkxOhBDSa5572wv-u7
"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import normalize

df = pd.read_csv('/content/Wholesale customers data.csv')

df.head()

df = df.drop('Region',axis=1)

df.head()

df.to_numpy(dtype=int)

df.shape

features = df.iloc[:,1:]
labels = df.iloc[:,0]
normalized_features = normalize(features, norm='l2')
normalized_data = np.concatenate((labels[:, np.newaxis], normalized_features), axis=1)

np.savetxt('normalized_data.txt', normalized_data)

